# Generated by Django 5.0.6 on 2024-05-20 01:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('codes', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Code',
        ),
    ]
